name: Publish to GitHub Container Registry
run-name: Publish to GitHub Container Registry - ${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  airbyte-hubspot-connector:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/jobengine
          tags: |
            type=raw,value=latest
            type=sha
            type=raw,value={{branch}}

      - id: publish
        name: Publish
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
